name: drumpad_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  ads_tracking_plugin:
    path: ../base-flutter-refactor
  intl: any
  flutter_localization: ^0.3.1
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_easyloading: ^3.0.5
  in_app_review: ^2.0.10
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.1.0
  path_provider: ^2.1.5
  get_it: ^8.0.3
  in_app_purchase: ^3.2.1
  purchases_flutter: ^8.6.0
  animated_flip_counter: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.1
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/anim/
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfprodisplayregular.otf
          weight: 400
        - asset: assets/fonts/sfprodisplaymedium.otf
          weight: 500
        - asset: assets/fonts/sfprodisplaybold.otf
          weight: 700
        - asset: assets/fonts/sfprodisplayblackitalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/sfprodisplayheavyitalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/sfprodisplaylightitalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/sfprodisplaysemibolditalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/sfprodisplaythinitalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/sfprodisplayultralightitalic.otf
          style: italic
          weight: 200
    - family: Ethnocentric
      fonts:
        - asset: assets/fonts/ethnocentric.ttf

    - family: ShrikhandRegular
      fonts:
        - asset: assets/fonts/shrikhand_regular.ttf
