name: drumpad_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  ads_tracking_plugin:
    path: ../base-flutter-refactor

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/anim/
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfprodisplayregular.otf
          weight: 400
        - asset: assets/fonts/sfprodisplaymedium.otf
          weight: 500
        - asset: assets/fonts/sfprodisplaybold.otf
          weight: 700
        - asset: assets/fonts/sfprodisplayblackitalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/sfprodisplayheavyitalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/sfprodisplaylightitalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/sfprodisplaysemibolditalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/sfprodisplaythinitalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/sfprodisplayultralightitalic.otf
          style: italic
          weight: 200
