// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:and_drum_pad_flutter/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(LessonSequenceAdapter());
    registerAdapter(NoteEventAdapter());
    registerAdapter(SongCollectionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(LessonSequenceAdapter());
    registerAdapter(NoteEventAdapter());
    registerAdapter(SongCollectionAdapter());
  }
}
