import 'package:drumpad_flutter/src/mvvm/models/lesson_model.dart';

final List<SongCollection> dataSongCollections = [
  SongCollection(
      id: '1231',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.easy,
      image: "assets/images/music_99%.png",
      author: "MCK",
      name: "99%"),
  SongCollection(
      id: '1232',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Lost%20Sky%20-%20Where%20We%20Started%20.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.hard,
      image: "assets/images/lactroi.png",
      author: "Anh Tùng Lúi",
      name: "Lost Sky - Where We Started"),
  SongCollection(
      id: '1233',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/1.%20Janji%20-%20Heroes%20Tonight%20(feat.%20Johnning)%20(Tempo%20128).zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.hard,
      image: "assets/images/lactroi.png",
      author: "Anh Chìm Loi",
      name: "Một Bài Nhạc Hay"),
  SongCollection(
      id: '1234',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.easy,
      image: "assets/images/lactroi.png",
      author: "Sơn Tùng M-TP Duplicate",
      name: "Anh Hai Lúa"),
  SongCollection(
      id: 'invincible',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.medium,
      image: "assets/images/lactroi.png",
      author: "Olodo",
      name: "ytinU"),
  SongCollection(
      id: 'tobu_hope',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Tobu_Hope.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.medium,
      image: "assets/images/music_99%.png",
      author: "Tobu",
      name: "Tobu Hope"),
];