import 'package:drumpad_flutter/src/mvvm/models/lesson_model.dart';

final List<SongCollection> dataSongCollections = [
  SongCollection(
      id: '1231',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 17,
      difficulty: DifficultyMode.easy,
      image: "assets/images/unity.jpg",
      author: "MCK",
      name: "99%"),
  SongCollection(
      id: 'where_we_started',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Lost%20Sky%20-%20Where%20We%20Started%20.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 13,
      difficulty: DifficultyMode.hard,
      image: "assets/images/where_we_started.jpeg",
      author: "Lost Anh Tùng Lúi",
      name: "Lost Sky - Where We Started"),
  SongCollection(
      id: 'heroes_tonight',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Heroes_Tonight.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 14,
      difficulty: DifficultyMode.hard,
      image: "assets/images/heroes_tonight.webp",
      author: "Janji",
      name: "Heroes Tonight"),
  SongCollection(
      id: '1234',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 17,
      difficulty: DifficultyMode.easy,
      image: "assets/images/lactroi.png",
      author: "Sơn Tùng M-TP Duplicate",
      name: "Anh Hai Lúa"),
  SongCollection(
      id: 'unity_1',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 17,
      difficulty: DifficultyMode.medium,
      image: "assets/images/unity.jpg",
      author: "Olodo",
      name: "ytinU"),
  SongCollection(
      id: 'tobu_hope',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Tobu_Hope.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 14,
      difficulty: DifficultyMode.medium,
      image: "assets/images/hope.jpeg",
      author: "Tobu",
      name: "Tobu Hope"),
  SongCollection(
      id: 'invinciblee',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Deaf%20Kev_Invincible.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 14,
      difficulty: DifficultyMode.demonic,
      image: "assets/images/invincible.jpeg",
      author: "Kev Điếc",
      name: "Invincible"),
  SongCollection(
      id: 'the_spectre',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Alan%20Walker_The%20Spectre.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 14,
      difficulty: DifficultyMode.hard,
      image: "assets/images/the_spectre.jpeg",
      author: "Anh Lân đi bộ",
      name: "The Spectre"),
  SongCollection(
      id: 'black_hole',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Black%20Hole.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 7,
      difficulty: DifficultyMode.easy,
      image: "assets/images/img_black_hole.png",
      author: "Black Hole",
      name: "Black Hole"),
  SongCollection(
      id: 'hypnus',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Hypnus.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 14,
      difficulty: DifficultyMode.easy,
      image: "assets/images/hypnus.jpeg",
      author: "Hupnus",
      name: "Hypnus"),
  SongCollection(
      id: 'money',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Money.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 7,
      difficulty: DifficultyMode.easy,
      image: "assets/images/money.jpg",
      author: "Money",
      name: "Money"),
  SongCollection(
      id: 'warriors',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Warriors.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 14,
      difficulty: DifficultyMode.easy,
      image: "assets/images/warriors.jpg",
      author: "Warriors",
      name: "Warriors"),
  SongCollection(
      id: 'mortals',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Mortals.zip',
      lessons: [],
      beatRunnerLessons: [],
      stepQuantity: 7,
      difficulty: DifficultyMode.easy,
      image: "assets/images/mortal.jpeg",
      author: "Mortals",
      name: "Mortals"),
];