import 'package:drumpad_flutter/src/mvvm/models/lesson_model.dart';

final List<SongCollection> dataSongCollections = [
  SongCollection(
      id: '1231',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.easy,
      image: "assets/images/unity.jpg",
      author: "MCK",
      name: "99%"),
  SongCollection(
      id: '1232',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Lost%20Sky%20-%20Where%20We%20Started%20.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.hard,
      image: "assets/images/where_we_started.jpeg",
      author: "Anh Tùng Lúi",
      name: "Lost Sky - Where We Started"),
  SongCollection(
      id: '1233',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Heroes_Tonight.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.hard,
      image: "assets/images/heroes_tonight.webp",
      author: "Anh Chìm Loi",
      name: "Một Bài Nhạc Hay"),
  SongCollection(
      id: '1234',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.easy,
      image: "assets/images/lactroi.png",
      author: "Sơn Tùng M-TP Duplicate",
      name: "Anh Hai Lúa"),
  SongCollection(
      id: 'invincible',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/unity.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.medium,
      image: "assets/images/unity.jpg",
      author: "Olodo",
      name: "ytinU"),
  SongCollection(
      id: 'tobu_hope',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Tobu_Hope.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.medium,
      image: "assets/images/hope.jpeg",
      author: "Tobu",
      name: "Tobu Hope"),
  SongCollection(
      id: 'invinciblee',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Deaf%20Kev_Invincible.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.demonic,
      image: "assets/images/invincible.jpeg",
      author: "Kev Điếc",
      name: "Invincible"),
  SongCollection(
      id: 'the_spectre',
      pathZipFile: 'https://github.com/hoanglm6201/zip_archive/raw/refs/heads/main/Alan%20Walker_The%20Spectre.zip',
      lessons: [],
      beatRunnerLessons: [],
      difficulty: DifficultyMode.hard,
      image: "assets/images/the_spectre.jpeg",
      author: "Anh Lân đi bộ",
      name: "The Spectre"),

];